---
- name: system information
  hosts: node1,node2,node3
  tasks:
   - name: system information
     copy:
      content: "{{ ansible_hostname }} \n {{ansible_processor_count}}
      dest: /var/tmp/sysinfo.html
      mode: 0644
...
